class splashscreen:
    def splashscreen():
        print("                                                                               ")
        print("                                                                               ")
        print("                                                                               ")                                                        
        print("            jjjj                                                               ")
        print("           j::::j                                                              ")
        print("            jjjj                                                               ")
        print("                                                                               ")
        print("          jjjjjjj  aaaaaaaaaaaaa  rrrrr   rrrrrrrrr                            ")
        print("          j:::::j  a::::::::::::a r::::rrr:::::::::r                           ")
        print("           j::::j  aaaaaaaaa:::::ar:::::::::::::::::r                          ")
        print("           j::::j           a::::arr::::::rrrrr::::::r                         ")
        print("           j::::j    aaaaaaa:::::a r:::::r     r:::::r                         ")
        print("           j::::j  aa::::::::::::a r:::::r     rrrrrrr                         ")
        print("           j::::j a::::aaaa::::::a r:::::r                                     ")
        print("           j::::ja::::a    a:::::a r:::::r                                     ")
        print("           j::::ja::::a    a:::::a r:::::r                                     ")
        print("           j::::ja:::::aaaa::::::a r:::::r                                     ")
        print("           j::::j a::::::::::aa:::ar:::::r                                     ")
        print("           j::::j  aaaaaaaaaa  aaaarrrrrrr                                     ")
        print("           j::::j                                      ________________________")
        print(" jjjj      j::::j                                      _::::::::::::::::::::::_")
        print("j::::jj   j:::::j                                      ________________________")
        print("j::::::jjj::::::j                                                              ")
        print(" jj::::::::::::j                                                               ")
        print("   jjj::::::jjj                                                                ")
        print("      jjjjjj                                                                   ")
        print("                                                                               ")
        print("                                                                               ")
        print("                                                                               ")
        print("Tugas Besar IF3130 Jaringan Komputer - Implementasi Protokol TCP-Like Go-Back-N")
        print("                            Kelompok jar_ (K03)                                ")
        print("                                                                               ")
        print("                                                                               ")
        print("                                                                               ")
        print("Memulai program ...                                                            ")
        print("                                                                               ")
        print("                                                                               ")